#!/usr/bin/env sh

[ -z "$PASSWD" ] && PASSWD="password"

umask 002
chown root:root /home && chmod 775 /home
grep -qF '[ -f "/home/.rc" ] && . /home/.rc' "/root/.bashrc" || echo '[ -f "/home/.rc" ] && . /home/.rc' >> /root/.bashrc
echo "root:$PASSWD" | chpasswd
[ -d "/tmp/home" ] && mv /tmp/home/.rc /home/.rc && ls -AF /tmp/home | while read dir; do [ -d "/home/$dir" ] || mkdir /home/$dir && mv /tmp/home/$dir/* /home/$dir/; done && rm -rf /tmp/home

if [ -z "$USER" ]; then
    USER="root"
    HOME="/root"
else
    HOME="/home/$USER"
    getent passwd $USER > /dev/null || useradd -m -d "$HOME" -s /bin/bash -G root,sudo $USER
    echo "$USER:$PASSWD" | chpasswd && chown $USER:$USER $HOME && chmod 700 $HOME
    [ -f "/etc/sudoers.d/$USER" ] || echo "$USER ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/$USER && chmod 440 /etc/sudoers.d/$USER
    [ -f "$HOME/.bashrc" ] || touch "$HOME/.bashrc" && chmod 644 "$HOME/.bashrc" && chown $USER:$USER "$HOME/.bashrc"
    grep -qF '[ -f "/home/.rc" ] && . /home/.rc' "$HOME/.bashrc" || echo '[ -f "/home/.rc" ] && . /home/.rc' >> "$HOME/.bashrc"
    [ -f "$HOME/.rc" ] || echo '# Set your private run commands here, then run the `rc` command' > "$HOME/.rc" && chmod 644 "$HOME/.rc" && chown $USER:$USER "$HOME/.rc"
fi

[ -f "/home/cert/cli.ini" ] && ln -snf /home/cert/cli.ini /etc/letsencrypt/cli.ini

[ -f "/home/conf/supervisord.conf" ] && ln -snf /home/conf/supervisord.conf /etc/supervisord.conf

[ -f "/home/conf/crontab.conf" ] && crontab /home/conf/crontab.conf

update

exec "$@"
