#!/usr/bin/env sh

umask 002

if [ -d "/tmp/home" ]; then
    [ -d "/home/bin" ] || mkdir /home/bin && mv /tmp/home/bin/* /home/bin/
    [ -d "/home/conf" ] || mkdir /home/conf && mv /tmp/home/conf/* /home/conf/
    mv /tmp/home/.rc /home/
    rm -rf /tmp/home
fi

[ -n "$UUID" ] && sed -i "s/\"id\": \"[^\"]*\"/\"id\": \"$UUID\"/g" /home/conf/xy.json

exec "$@"
